server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lazeez?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true

